### ISSUE TITLE
Update platinum and silver sponsors accordingly. 

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/pwlconf#31]

**Comment by DarrenN** [comment]
Are these listed in a spreadsheet?

**Comment by zeeshanlakhani** [comment]
Now, yep.

**Comment by zeeshanlakhani** [comment]
Updated spreadsheet btw.

**Comment by zeeshanlakhani** [comment]
Current numbers @DarrenN:

Platinum: 1
Silver: 7
Lanyard: Gone

**Comment by zeeshanlakhani** [comment]
Reopening to update numbers of what's available and also, let's remove the Opp. Grant section as SL has closed those.
