### ISSUE TITLE
Outreach: Missouri, Illinois (local) contacts for universities and local tech companies

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/pwlconf#42]
^^ @tsantero, @deltamualpha

**Comment by mfollett** [comment]
- [x] Advertise on the STL Tech Slack.
 - [ ] Get ad in SLUUG.
 - [ ] Reach out to Wash U.
 - [x] Reach out to SLU.
 - [ ] Reach out at the SIU* schools.
 - [ ] Reach out to Webster U.
 - [ ] Reach out to Fontbonne.

Should we be reaching out to schools now or after the summer?

**Comment by zeeshanlakhani** [comment]
@mfollett I say the earlier the better.

**Comment by mfollett** [comment]
SLU has confirmed that they're announcing it to students now and when school is back in session. I don't have a reliable contact at WUSTL anymore. Will reach out to some SIU* contacts next week.

**Comment by Randommood** [comment]
Hey @mfollett what about Rolla?

**Comment by deltamualpha** [comment]
I'll hit up SLUUG tomorrow.

**Comment by zeeshanlakhani** [comment]
@deltamualpha @jeremyheiler please update as you make contact.

**Comment by zeeshanlakhani** [comment]
Also, any companies we can target and let them know that their employees should come?

**Comment by jeremyheiler** [comment]
@mfollett I'd like to help, but I'm not good at writing these kinds of emails. Do you have a template we can use?

**Comment by zeeshanlakhani** [comment]
@jeremyheiler I don't think we have a template. Maybe you and @deltamualpha can draw up something that is simple?

**Comment by hakutsuru** [comment]
Something like this could be sent to CS, Engineering and Math departments.

(And if this sucks, it is at least a starting point to develop something great...)

Maybe it would be cool to have a PDF advertisement for posting on college bulletin boards.

****

Dear Dean,

Papers We Love is hosting our conference in St. Louis on September 28th. We hope that you will share this information with colleagues, staff and students.

<http://pwlconf.org>

As a non-profit educational organization, our aim is to foster a closer relationship with academia and industry to promote technical literacy and advancement. Our conference will feature an accessible collection of talks on how seemingly esoteric topics in academic research can be used by engineers to solve technical challenges.

We anticipate our speakers to include fascinating pragmatic details in their talks -- such as Kenichi Asai on "Delimited Continuations for Everyone", and Fabienne Serriere on applying "The Algorithmic Beauty of Seashells" to industrial knitting patterns.

Our last conference was a great success, and we would love to see you at this year's event. Any help you could provide with our outreach is greatly appreciated.

Sincerely,

Papers We Love

**Comment by deltamualpha** [comment]
Email sent to editor@sluug.org about the conference.

**Comment by zeeshanlakhani** [comment]
cool @deltamualpha!

**Comment by mfollett** [comment]
Might want to include something in the template about how to get a free ticket if you are a student since we are primarily targeting universities with this.

**Comment by zeeshanlakhani** [comment]
Any updates here @deltamualpha @tsantero @mfollett @jeremyheiler ?
