### ISSUE TITLE
New photo for Elaine Chew

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/pwlconf#48]
<img width="611" alt="screen shot 2017-07-13 at 9 45 42 am" src="https://user-images.githubusercontent.com/202820/28184295-0d240cba-67d0-11e7-9ae2-166e239e2bc8.png">

**Comment by DarrenN** [comment]
Fixed in 99421b0e443ffb9f9a1917c0f53892edae0b17e7
