### ISSUE TITLE
Sponsorships round 1

### ISSUE THREAD

**Issue by zeeshanlakhani** [papers-we-love/pwlconf#88]
- lanyard -> Hashicorp
- bronze and captioning -> Comcast Cable
- Silvers: Cerner, ACM
- Video: Datadog
- Individual: Cuyler Jones - https://twitter.com/cuylerjones

For these, we can use all the same logos, descriptions as before.

@DarrenN we should also update the numbers on the prospectus (and remove captioning and lanyard sponsorships).

**Comment by DarrenN** [comment]
ACK

**Comment by DarrenN** [comment]
![screenshot 2018-05-28 15 46 37](https://user-images.githubusercontent.com/215030/40627680-5967e7fe-628e-11e8-9ea3-e681b45585f5.png)
